#home:
#    path: /
#    controller: App\Controller\HomeController::home
users:
  type: rest
  resource: App\Controller\UserController
subcriptions:
  type: rest
  resource: App\Controller\SubscriptionController
cards:
  type: rest
  resource: App\Controller\CardController
